[package]
name = "cordl"
author = "Sc2ad"
version = "0.1.0"
edition = "2021"

[dependencies]
il2cpp_metadata_raw = { git = "https://github.com/StackDoubleFlow/brocolib.git" }
il2cpp_binary = { git = "https://github.com/StackDoubleFlow/brocolib.git" }
clap = { version = "3.1.8", features = ["derive"] }
anyhow = { version = "*" }
indent_write = { version = "*" }
color-eyre = "0.6"
itertools = "0.10"